services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: naruto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha-rede

  app:
    image: naruto
    container_name: springboot_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/naruto
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - minha-rede

volumes:
  postgres_data:

networks:
  minha-rede:
